apiVersion: v1
kind: Service
metadata:
  name: transportationorderserver-srv
spec:
  selector:
    app: transportationorderserver
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer